# Generated by Django 4.2.17 on 2024-12-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='name',
            new_name='user',
        ),
    ]
