# Generated by Django 4.2.17 on 2024-12-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_name_groupmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='date_saved',
            new_name='saved_at',
        ),
    ]
